### ISSUE TITLE
Vue3 support

### ISSUE THREAD

**Issue by devmount** [testdrivenio/fastapi-vue#3]
Anybody interested in having this awesome project support Vue3? I can create a PR for that.

And many thanks @mjhea0 for writing the great tutorial for this project 👏🏻

**Comment by paolodina** [comment]
It would be great to have a modern version (Vue3/Vite + Pinia) of this project. I don't know how much I can contribute, but I'm interested. If you have something, maybe could you share that so we can have a look?

**Comment by devmount** [comment]
Well I'm quite experienced in migrating Vue2 projects to Vue3 / composition API, so I can offer to do that (maybe it's best to keep this on a different branch though). If you would like to use Vite or Pinia as well, feel free to add / implement it on top.

**Comment by paolodina** [comment]
Wonderful, couldn't hope for better news.

**Comment by KristjanESPERANTO** [comment]
This tutorial is very good and I think it would be worth the effort to migrate to Vue3. Is there any progress here yet? :slightly_smiling_face:

**Comment by devmount** [comment]
Yeah, I didn't have time yet. I try to have a PR ready in November. @paolodina @KristjanESPERANTO Can you review / test the PR when it's ready?

**Comment by paolodina** [comment]
@devmount thanks, ATM I'm less in hurry for this. So welcome for November (or when you can do that), in the meantime I had take up Vue 3 and yep, I can review. Btw, coming back from Svelte (which I found great but less mature), I can say Vue 3 is so nice and so similar to Svelte if you want to make it so.

**Comment by KristjanESPERANTO** [comment]
There are some new things for me to learn from this tutorial, but it will be also a good opportunity to test your new version. I'll be happy to do that. Thank you for your commitment, @devmount!

**Comment by devmount** [comment]
@paolodina @KristjanESPERANTO I've implemented the changes to support Vue3 in #10. Feel free to review it, hope this is useful for you.

**Comment by KristjanESPERANTO** [comment]
@devmount: Nice job! 👍

In order to test this correctly, [the tutorial](https://testdriven.io/blog/developing-a-single-page-app-with-fastapi-and-vuejs/) would also have to be updated. For this it would make sense to put the tutorial into a markdown file.

@mjhea0: What do you think? Do you have the tutorial as markdown?

**Comment by paolodina** [comment]
@devmount I went back to Django again (mainly for the ORM). Probably I won't test your change along with FastAPI, nonetheless the PR looks good, thanks.

**Comment by mjhea0** [comment]
Thanks for this, @KristjanESPERANTO! We're going to start updating the tutorial this weekend. I'll keep you posted.
